----------------------------------------------------------------------------------------------------------------------
--'	Схема обыска трупов
--'	автор: Диденко Руслан (Stohe)
--'	TODO:
----------------------------------------------------------------------------------------------------------------------
lootable_table = {}

--ammos
lootable_table["ammo_9x18_fmj"] = true
lootable_table["ammo_9x18_pmm"] = true
lootable_table["ammo_9x19_pbp"] = true
lootable_table["ammo_9x19_fmj"] = true
lootable_table["ammo_11.43x23_hydro"] = true
lootable_table["ammo_11.43x23_fmj"] = true
lootable_table["ammo_12x70_buck"] = true
lootable_table["ammo_12x76_zhekan"] = true
lootable_table["ammo_12x70_buckshot"] = true
lootable_table["ammo_5.45x39_ap"] = true
lootable_table["ammo_5.45x39_fmj"] = true
lootable_table["ammo_5.7x28_fmj"] = true
lootable_table["ammo_5.7x28_ap"] = true
lootable_table["ammo_7.62x39_fmj"] = true
lootable_table["ammo_7.62x39_ap"] = true
lootable_table["ammo_9x39_ap"] = true
lootable_table["ammo_9x39_pab9"] = true
lootable_table["ammo_5.56x45_ss190"] = true
lootable_table["ammo_5.56x45_ap"] = true
lootable_table["ammo_7.62x54_7h1"] = true
lootable_table["ammo_7.62x54_7h14"] = true
lootable_table["ammo_7.62x54_ap"] = true
lootable_table["ammo_7.62x25_p"] = true
lootable_table["ammo_7.62x25_ps"] = true
lootable_table["ammo_7.62x51_fmj"] = true
lootable_table["ammo_7.62x51_ap"] = true
lootable_table["ammo_gauss"] = true
lootable_table["ammo_gauss_cardan"] = true
lootable_table["ammo_og-7b"] = true
lootable_table["ammo_vog-25"] = true
lootable_table["grenade_f1"] = true
lootable_table["grenade_rgd5"] = true
lootable_table["ammo_m209"] = true
lootable_table["ammo_pkm_100"] = true

--weapons
lootable_table["wpn_9a91"] = true
lootable_table["wpn_abakan"] = true
lootable_table["wpn_aek971"] = true
lootable_table["wpn_ak"] = true
lootable_table["wpn_ak74"] = true
lootable_table["wpn_ak74m"] = true
lootable_table["wpn_ak101"] = true
lootable_table["wpn_ak102"] = true
lootable_table["wpn_ak103"] = true
lootable_table["wpn_ak104"] = true
lootable_table["wpn_ak105"] = true
lootable_table["wpn_akm"] = true
lootable_table["wpn_akms"] = true
lootable_table["wpn_aks"] = true
lootable_table["wpn_aks74"] = true
lootable_table["wpn_ak74u"] = true
lootable_table["wpn_aug"] = true
lootable_table["wpn_beretta"] = true
lootable_table["wpn_binoc"] = true
lootable_table["wpn_bizon"] = true
lootable_table["wpn_colt1911"] = true
lootable_table["wpn_cz52"] = true
lootable_table["wpn_cz75"] = true
lootable_table["wpn_desert_eagle"] = true
lootable_table["wpn_fn2000"] = true
lootable_table["wpn_fn57"] = true
lootable_table["wpn_fnp45"] = true
lootable_table["wpn_fort"] = true
lootable_table["wpn_g3a3"] = true
lootable_table["wpn_g3sg1"] = true
lootable_table["wpn_g36"] = true
lootable_table["wpn_g36c"] = true
lootable_table["wpn_g36k"] = true
lootable_table["wpn_gauss"] = true
lootable_table["wpn_glock"] = true
lootable_table["wpn_mp443"] = true
lootable_table["wpn_groza"] = true
lootable_table["wpn_gsh18"] = true
lootable_table["wpn_hpsa"] = true
lootable_table["wpn_knife"] = true
lootable_table["wpn_knife2"] = true
lootable_table["wpn_knife3"] = true
lootable_table["wpn_knife4"] = true
lootable_table["wpn_knife5"] = true
lootable_table["wpn_hand_axe"] = true
lootable_table["wpn_hand_shovel"] = true
lootable_table["wpn_hand_crowbar"] = true
lootable_table["wpn_hand_hammer"] = true
lootable_table["wpn_l85"] = true
lootable_table["wpn_l96"] = true
lootable_table["wpn_lr300"] = true
lootable_table["wpn_m4"] = true
lootable_table["wpn_m4a1"] = true
lootable_table["wpn_m16"] = true
lootable_table["wpn_m16a2"] = true
lootable_table["wpn_m98b"] = true
lootable_table["wpn_wincheaster1300"] = true
lootable_table["wpn_mp5"] = true
lootable_table["wpn_p90"] = true
lootable_table["wpn_walther"] = true
lootable_table["wpn_sig220"] = true
lootable_table["wpn_pb"] = true
lootable_table["wpn_pkm"] = true
lootable_table["wpn_pm"] = true
lootable_table["wpn_pmm"] = true
lootable_table["wpn_protecta"] = true
lootable_table["wpn_remington870"] = true
lootable_table["wpn_rg-6"] = true
lootable_table["wpn_rpg7"] = true
lootable_table["wpn_rpk"] = true
lootable_table["wpn_rpk74"] = true
lootable_table["wpn_saiga"] = true
lootable_table["wpn_scar"] = true
lootable_table["wpn_sig550"] = true
lootable_table["wpn_spas12"] = true
lootable_table["wpn_sr1m"] = true
lootable_table["wpn_sr25"] = true
lootable_table["wpn_svd"] = true
lootable_table["wpn_svu"] = true
lootable_table["wpn_toz34"] = true
lootable_table["wpn_bm16"] = true
lootable_table["wpn_bm16_full"] = true
lootable_table["wpn_tt33"] = true
lootable_table["wpn_ump45"] = true
lootable_table["wpn_usp"] = true
lootable_table["wpn_val"] = true
lootable_table["wpn_vihr"] = true
lootable_table["wpn_vintorez"] = true
lootable_table["wpn_wa2000"] = true

-- addons
lootable_table["wpn_addon_scope"] = true
lootable_table["wpn_addon_scope_x2.7"] = true
lootable_table["wpn_addon_scope_detector"] = true
lootable_table["wpn_addon_scope_night"] = true
lootable_table["wpn_addon_scope_susat"] = true
lootable_table["wpn_addon_scope_susat_x1.6"] = true
lootable_table["wpn_addon_scope_susat_custom"] = true
lootable_table["wpn_addon_scope_susat_dusk"] = true
lootable_table["wpn_addon_scope_susat_night"] = true
lootable_table["wpn_addon_silencer"] = true
lootable_table["wpn_addon_grenade_launcher"] = true
lootable_table["wpn_addon_grenade_launcher_m203"] = true

-- outfits
lootable_table["novice_outfit"] = true
lootable_table["stalker_outfit"] = true
lootable_table["scientific_outfit"] = true
lootable_table["neutral_assault_outfit"] = true
lootable_table["bandit_outfit"] = true
lootable_table["bandit_brownrain_outfit"] = true
lootable_table["bandit_blackrain_outfit"] = true
lootable_table["bandit_light_outfit"] = true
lootable_table["svoboda_light_outfit"] = true
lootable_table["svoboda_outfit"] = true
lootable_table["svoboda_scientific_outfit"] = true
lootable_table["svoboda_heavy_outfit"] = true
lootable_table["svoboda_assault_outfit"] = true
lootable_table["dolg_outfit"] = true
lootable_table["dolg_scientific_outfit"] = true
lootable_table["dolg_heavy_outfit"] = true
lootable_table["dolg_assault_outfit"] = true
lootable_table["monolit_outfit"] = true
lootable_table["monolith_scientific_outfit"] = true
lootable_table["monolith_assault_outfit"] = true
lootable_table["merc_outfit"] = true
lootable_table["merc_assault_outfit"] = true
lootable_table["ecolog_outfit"] = true
lootable_table["cs_light_outfit"] = true
lootable_table["cs_heavy_outfit"] = true
lootable_table["specops_outfit"] = true
lootable_table["military_outfit"] = true

-- helmets
lootable_table["helm_cloth_mask"] = true
lootable_table["helm_respirator"] = true
lootable_table["helm_m40"] = true
lootable_table["helm_hardhat"] = true
lootable_table["helm_tactic"] = true
lootable_table["helm_battle"] = true

--medkits
lootable_table["bandage"] = true
lootable_table["medkit"] = true
lootable_table["medkit_scientic"] = true
lootable_table["medkit_army"] = true
lootable_table["antirad"] = true
lootable_table["stimpack"] = true
lootable_table["stimpack_army"] = true
lootable_table["stimpack_scientic"] = true
lootable_table["adrenalin"] = true

--drugs
lootable_table["caffeine"] = true
lootable_table["caffeine_2"] = true
lootable_table["caffeine_3"] = true
lootable_table["caffeine_4"] = true
lootable_table["caffeine_5"] = true
lootable_table["drug_booster"] = true
lootable_table["drug_charcoal"] = true
lootable_table["drug_charcoal_2"] = true
lootable_table["drug_charcoal_3"] = true
lootable_table["drug_charcoal_4"] = true
lootable_table["drug_charcoal_5"] = true
lootable_table["drug_coagulant"] = true
lootable_table["drug_coagulant_2"] = true
lootable_table["drug_coagulant_3"] = true
lootable_table["drug_coagulant_4"] = true
lootable_table["drug_coagulant_5"] = true
lootable_table["drug_psy_blockade"] = true
lootable_table["drug_psy_blockade_2"] = true
lootable_table["drug_psy_blockade_3"] = true
lootable_table["drug_psy_blockade_4"] = true
lootable_table["drug_psy_blockade_5"] = true
lootable_table["drug_antidot"] = true
lootable_table["drug_antidot_2"] = true
lootable_table["drug_antidot_3"] = true
lootable_table["drug_radioprotector"] = true
lootable_table["drug_radioprotector_2"] = true
lootable_table["drug_anabiotic"] = true

--food and drink
lootable_table["bread"] = true
lootable_table["breadold"] = true
lootable_table["kolbasa"] = true
lootable_table["conserva"] = true
lootable_table["tushonka"] = true
lootable_table["protein"] = true
lootable_table["tomato"] = true
lootable_table["sausage"] = true
lootable_table["corn"] = true
lootable_table["beans"] = true
lootable_table["chili"] = true
lootable_table["salmon"] = true
lootable_table["raisins"] = true
lootable_table["chocolate"] = true
lootable_table["nuts"] = true
lootable_table["mre"] = true
lootable_table["mre_2"] = true
lootable_table["mre_3"] = true
lootable_table["ration_ukr"] = true
lootable_table["ration_ukr_2"] = true
lootable_table["ration_ukr_3"] = true
lootable_table["ration_ukr_4"] = true
lootable_table["ration_ukr_5"] = true
lootable_table["ration_ukr_6"] = true
lootable_table["vodka"] = true
lootable_table["vodka_2"] = true
lootable_table["vodka_3"] = true
lootable_table["vodka_quality"] = true
lootable_table["vodka_quality_2"] = true
lootable_table["vodka_quality_3"] = true
lootable_table["bottle_metal"] = true
lootable_table["bottle_metal_2"] = true
lootable_table["bottle_metal_3"] = true
lootable_table["mineral_water"] = true
lootable_table["mineral_water_2"] = true
lootable_table["mineral_water_3"] = true
lootable_table["flask"] = true
lootable_table["flask_2"] = true
lootable_table["flask_3"] = true
lootable_table["cigarettes"] = true
lootable_table["cigarettes_2"] = true
lootable_table["cigarettes_3"] = true
lootable_table["cigarettes_lucky"] = true
lootable_table["cigarettes_lucky_2"] = true
lootable_table["cigarettes_lucky_3"] = true
lootable_table["cigarettes_russian"] = true
lootable_table["cigarettes_russian_2"] = true
lootable_table["cigarettes_russian_3"] = true
lootable_table["tobacco"] = true
lootable_table["tobacco_2"] = true
lootable_table["tobacco_3"] = true
lootable_table["hand_rolling_tobacco"] = true
lootable_table["hand_rolling_tobacco_2"] = true
lootable_table["hand_rolling_tobacco_3"] = true
lootable_table["energy_drink"] = true

--repair items
lootable_table["sharpening_stones"] = true
lootable_table["sharpening_stones_2"] = true
lootable_table["sharpening_stones_3"] = true
lootable_table["sharpening_stones_4"] = true
lootable_table["cleaning_kit_p"] = true
lootable_table["cleaning_kit_p_2"] = true
lootable_table["cleaning_kit_p_3"] = true
lootable_table["cleaning_kit_s"] = true
lootable_table["cleaning_kit_s_2"] = true
lootable_table["cleaning_kit_s_3"] = true
lootable_table["cleaning_kit_r"] = true
lootable_table["cleaning_kit_r_2"] = true
lootable_table["cleaning_kit_r_3"] = true
lootable_table["toolkit_p"] = true
lootable_table["toolkit_s"] = true
lootable_table["toolkit_r"] = true
lootable_table["toolkit_p_0"] = true
lootable_table["toolkit_s_0"] = true
lootable_table["toolkit_r_0"] = true
lootable_table["sewing_kit_b"] = true
lootable_table["sewing_kit_b_2"] = true
lootable_table["sewing_kit_b_3"] = true
lootable_table["sewing_kit_b_4"] = true
lootable_table["sewing_kit_a"] = true
lootable_table["sewing_kit_a_2"] = true
lootable_table["sewing_kit_a_3"] = true
lootable_table["sewing_kit_a_4"] = true
lootable_table["sewing_kit_h"] = true
lootable_table["sewing_kit_h_2"] = true
lootable_table["sewing_kit_h_3"] = true
lootable_table["sewing_kit_h_4"] = true
lootable_table["glue_a"] = true
lootable_table["glue_a_2"] = true
lootable_table["glue_e"] = true
lootable_table["glue_e_2"] = true
lootable_table["armor_repair_fa"] = true
lootable_table["armor_repair_fa_2"] = true
lootable_table["armor_repair_pro"] = true
lootable_table["helmet_repair_kit"] = true
lootable_table["armor_repair_pro_0"] = true
lootable_table["helmet_repair_kit_0"] = true

--monsters
lootable_table["mutant_part_tushkano_meat"] = true
lootable_table["mutant_part_dog_meat"] = true
lootable_table["mutant_part_snork_hand"] = true
lootable_table["mutant_part_psevdodog_meat"] = true
lootable_table["mutant_part_flesh_meat"] = true
lootable_table["mutant_part_boar_chop"] = true
lootable_table["mutant_part_krovosos_meat"] = true
lootable_table["mutant_part_chimera_meat"] = true
lootable_table["meat_tushkano"] = true
lootable_table["meat_dog"] = true
lootable_table["meat_snork"] = true
lootable_table["meat_pseudodog"] = true
lootable_table["meat_flesh"] = true
lootable_table["meat_boar"] = true
lootable_table["meat_bloodsucker"] = true
lootable_table["meat_chimera"] = true
lootable_table["mutant_flesh_eye"] = true
lootable_table["hide_flesh"] = true
lootable_table["mutant_boar_leg"] = true
lootable_table["mutant_part_boar_tusk"] = true
lootable_table["hide_boar"] = true
lootable_table["mutant_dog_tail"] = true
lootable_table["mutant_part_dog_liver"] = true
lootable_table["mutant_part_dog_heart"] = true
lootable_table["mutant_psevdodog_tail"] = true
lootable_table["mutant_part_psevdodog_fang"] = true
lootable_table["hide_pseudodog"] = true
lootable_table["mutant_part_psy_dog_brain"] = true
lootable_table["hide_psy_dog"] = true
lootable_table["mutant_krovosos_jaw"] = true
lootable_table["mutant_part_krovosos_heart"] = true
lootable_table["hide_bloodsucker"] = true
lootable_table["mutant_snork_leg"] = true
lootable_table["mutant_part_snork_mask"] = true
lootable_table["mutant_burer_hand"] = true
lootable_table["mutant_part_burer_brain"] = true
lootable_table["hide_burer"] = true
lootable_table["mutant_chimera_nail"] = true
lootable_table["mutant_part_chimera_corn"] = true
lootable_table["mutant_part_chimera_heart"] = true
lootable_table["hide_chimera"] = true
lootable_table["mutant_face_tushkano"] = true
lootable_table["mutant_hand_kontroler"] = true
lootable_table["mutant_part_controller_glass"] = true
lootable_table["hide_controller"] = true
lootable_table["mutant_poltergeist_glas"] = true
lootable_table["powder_poltergeist"] = true
lootable_table["mutant_psevdogigant_hand"] = true	
lootable_table["mutant_part_pseudogigant_eye"] = true
lootable_table["hide_pseudogiant"] = true

--other items
lootable_table["detector_simple"] = true
lootable_table["detector_advanced"] = true
lootable_table["detector_elite"] = true
lootable_table["detector_scientific"] = true
lootable_table["guitar_a"] = true
lootable_table["harmonica_a"] = true
lootable_table["dosimeter"] = true
lootable_table["geiger"] = true
lootable_table["anomaly_elite"] = true
lootable_table["arc_art_box_basic"] = true
lootable_table["arc_art_box_8basic"] = true
lootable_table["arc_art_box_1basic"] = true
lootable_table["af_iam"] = true
lootable_table["af_aac"] = true
lootable_table["af_aam"] = true
lootable_table["lead_box"] = true
lootable_table["matches"] = true
lootable_table["cooking"] = true
lootable_table["kerosene"] = true
lootable_table["kerosene_2"] = true
lootable_table["kerosene_3"] = true
lootable_table["kerosene_4"] = true
lootable_table["kerosene_5"] = true
lootable_table["charcoal"] = true
lootable_table["charcoal_2"] = true
lootable_table["charcoal_3"] = true
lootable_table["explo_jerrycan_fuel_0"] = true
lootable_table["explo_jerrycan_fuel"] = true
lootable_table["explo_jerrycan_fuel_2"] = true
lootable_table["explo_jerrycan_fuel_3"] = true
lootable_table["explo_jerrycan_fuel_4"] = true
lootable_table["explo_jerrycan_fuel_5"] = true
lootable_table["explo_jerrycan_fuel_6"] = true
lootable_table["explo_jerrycan_fuel_7"] = true
lootable_table["explo_jerrycan_fuel_8"] = true
lootable_table["explo_balon_gas_0"] = true
lootable_table["explo_balon_gas"] = true
lootable_table["explo_balon_gas_2"] = true
lootable_table["explo_balon_gas_3"] = true
lootable_table["explo_balon_gas_4"] = true
lootable_table["explo_balon_gas_5"] = true
lootable_table["explo_balon_gas_6"] = true
lootable_table["explo_balon_gas_7"] = true
lootable_table["explo_balon_gas_8"] = true
lootable_table["rope"] = true
lootable_table["roubles"] = true
lootable_table["ammo_bad"] = true
lootable_table["old_book"] = true
lootable_table["grooming"] = true
lootable_table["spareparts"] = true
lootable_table["cards"] = true
lootable_table["boots"] = true
lootable_table["swiss"] = true
lootable_table["headlamp"] = true
lootable_table["jewelry_box"] = true
lootable_table["book1"] = true
lootable_table["book2"] = true
lootable_table["picture_woman"] = true
lootable_table["porn"] = true
lootable_table["porn2"] = true
lootable_table["tarpaulin"] = true
lootable_table["synthrope"] = true
lootable_table["cutlery"] = true
lootable_table["radio"] = true
lootable_table["grease"] = true
lootable_table["steel_wool"] = true
lootable_table["textile_patch_b"] = true
lootable_table["textile_patch_m"] = true
lootable_table["textile_patch_e"] = true
lootable_table["copper_coil"] = true
lootable_table["textolite"] = true
lootable_table["transistors"] = true
lootable_table["capacitors"] = true
lootable_table["colophony"] = true

--unique items
lootable_table["wpn_ak74m_camo"] = true
lootable_table["wpn_ak74u_snag"] = true
lootable_table["wpn_colt1911_sk1"] = true
lootable_table["wpn_colt1911_sk2"] = true
lootable_table["wpn_desert_eagle_nimble"] = true
lootable_table["wpn_fnp45_nimble"] = true
lootable_table["wpn_fort_snag"] = true
lootable_table["wpn_g36_nimble"] = true
lootable_table["wpn_groza_nimble"] = true
lootable_table["wpn_wincheaster1300_trapper"] = true
lootable_table["wpn_mp5_nimble"] = true
lootable_table["wpn_sig220_nimble"] = true
lootable_table["wpn_pkm_zulus"] = true
lootable_table["wpn_pm_actor"] = true
lootable_table["wpn_protecta_nimble"] = true
lootable_table["wpn_scar_nimble"] = true
lootable_table["wpn_sig550_luckygun"] = true
lootable_table["wpn_spas12_nimble"] = true
lootable_table["wpn_svu_nimble"] = true
lootable_table["wpn_usp_nimble"] = true
lootable_table["wpn_vintorez_nimble"] = true
lootable_table["exo_outfit_nimble"] = true
lootable_table["stalker_medic_outfit"] = true
lootable_table["stalker_outfit_barge"] = true
lootable_table["helm_respirator_joker"] = true
lootable_table["helm_hardhat_snag"] = true



local corpse_contain_any_valuable

function check_item(npc, item)
--	printf("found item %s", item:name())
	if lootable_table[item:section()] == true then
		corpse_contain_any_valuable = true
	end
end

----------------------------------------------------------------------------------------------------------------------
-- EVALUATORS
----------------------------------------------------------------------------------------------------------------------
class "evaluator_corpse" (property_evaluator)
function evaluator_corpse:__init(name, storage, npc) super (nil, name)
	self.a = storage
end
function evaluator_corpse:evaluate()
	if not self.object:alive() then
		return false
	end

	if self.object:best_enemy() ~= nil then
		return false
	end

	if self.object:character_community() == "zombied" then
		return false
	end

	if self.a.corpse_detection_enabled == false then
		return false
	end

	if xr_wounded.is_wounded(self.object) then
		return false
	end

	if self.object:section() == "actor_visual_stalker" then
		return false
	end

	local corpses = release_body_manager.get_release_body_manager().release_objects_table

	local nearest_corpse_dist = 400 -- Будет выбирать только трупы, ближе чем эта дистанция (проверяется по квадрату расстояния)
	local nearest_corpse_vertex = nil
	local nearest_corpse_position = nil
	local corpse_id	= nil

	for k,v in pairs(corpses) do
		local id = v.id
		local corpse_npc = db.storage[id] and db.storage[id].object

		if corpse_npc ~= nil and self.object:see(corpse_npc) and (db.storage[id].corpse_already_selected == nil or db.storage[id].corpse_already_selected == self.object:id()) then
			if self.object:position():distance_to_sqr(corpse_npc:position()) < nearest_corpse_dist then

				corpse_contain_any_valuable = nil
				corpse_npc:iterate_inventory(check_item, corpse_npc)

				if corpse_contain_any_valuable == true then

					--printf("FOUND NEW PRIOR CORPSE %s", corpse_npc:name())
					corpse_vertex = level.vertex_id(corpse_npc:position())
					if self.object:accessible(corpse_vertex) then
						nearest_corpse_dist = self.object:position():distance_to_sqr(corpse_npc:position())
						nearest_corpse_vertex = corpse_vertex
						nearest_corpse_position = corpse_npc:position()
						corpse_id = id
					end

				end
--			else
--				printf("FOUND CORPSE %s FAR %s", corpse_npc:name(), self.object:position():distance_to_sqr(corpse_npc:position()))
			end

		end
	end

	if nearest_corpse_vertex ~= nil then
		self.a.vertex_id = nearest_corpse_vertex
		self.a.vertex_position = nearest_corpse_position
		
		if self.a.selected_corpse_id ~= nil and self.a.selected_corpse_id ~= corpse_id then
			if db.storage[self.a.selected_corpse_id] ~= nil then
				db.storage[self.a.selected_corpse_id].corpse_already_selected = nil
			end			
		end

		self.a.selected_corpse_id = corpse_id
		db.storage[self.a.selected_corpse_id].corpse_already_selected = self.object:id()		
		
		return true
	end

	return false
end



----------------------------------------------------------------------------------------------------------------------
--Actions
----------------------------------------------------------------------------------------------------------------------
class "action_search_corpse" (action_base)
function action_search_corpse:__init (npc_name,action_name, storage) super (nil, action_name)
	self.a = storage
end
function action_search_corpse:initialize()
	action_base.initialize(self)
	self.object:set_desired_position()
	self.object:set_desired_direction()

	self.object:set_dest_level_vertex_id(self.a.vertex_id)
	--state_mgr.set_state(self.object, "patrol", nil, nil, {look_position = self.a.vertex_position})
	state_mgr.set_state(self.object, "patrol")
end
function action_search_corpse:execute ()
	action_base.execute(self)

	if self.object:position():distance_to_sqr(self.a.vertex_position) > 2 then
		return
	end

	state_mgr.set_state(self.object, "search_corpse", nil, nil, {look_position = self.a.vertex_position})
	xr_sound.set_sound_play(self.object:id(), "corpse_loot_begin")
end
function action_search_corpse:finalize ()
	if self.a.selected_corpse_id ~= nil and db.storage[self.a.selected_corpse_id] ~= nil then 
		db.storage[self.a.selected_corpse_id].corpse_already_selected = nil
	end
	
	action_base.finalize(self)
end

local transfer_to_npc = nil

function get_all_from_corpse(npc)
	printf("GET ALL FROM CORPSE")

	local corpse_npc_id = db.storage[npc:id()].corpse_detection.selected_corpse_id
	local corpse_npc = db.storage[corpse_npc_id] and db.storage[corpse_npc_id].object

	if corpse_npc == nil then
		return
	end
	
	transfer_to_npc = npc
	
	function get_item(npc, item)
		SendScriptCallback("npc_on_get_all_from_corpse",npc,corpse_npc,item,lootable_table[item:section()])
		if lootable_table[item:section()] == true then
			npc:transfer_item(item, transfer_to_npc)
		end
	end
	corpse_npc:iterate_inventory(get_item, corpse_npc)
	
	if math.random(100) > 20 then
		xr_sound.set_sound_play(npc:id(), "corpse_loot_begin")
	else
		xr_sound.set_sound_play(npc:id(), "corpse_loot_bad")
	end
end

----------------------------------------------------------------------------------------------------------------------
-- BINDER
----------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, char_ini, scheme, section, st)
	local operators	= {}
	local properties  = {}


	properties["corpse_exist"]				= xr_evaluators_id.corpse_exist
	properties["wounded"]					= xr_evaluators_id.sidor_wounded_base

	operators["search_corpse"]				= xr_actions_id.corpse_exist
	operators["state_mgr_to_idle_alife"]	= xr_actions_id.state_mgr + 2

	local manager = npc:motivation_action_manager()


	-- Evaluators
	manager:add_evaluator (properties["corpse_exist"], 		evaluator_corpse("corpse_exist", st))

	-- Actions
	local action = action_search_corpse (npc:name(),"action_search_corpse", st)
	action:add_precondition		(world_property(stalker_ids.property_alive, true))
	action:add_precondition		(world_property(stalker_ids.property_enemy,	false))
	action:add_precondition		(world_property(stalker_ids.property_danger,false))
	action:add_precondition		(world_property(stalker_ids.property_anomaly,false))
	action:add_precondition		(world_property(stalker_ids.property_items,false))
	action:add_precondition		(world_property(properties["corpse_exist"],	true))
	action:add_precondition		(world_property(properties["wounded"], 		false))
	action:add_precondition 	(world_property(xr_evaluators_id.wounded_exist,		false))
	action:add_effect (world_property(properties["corpse_exist"], 			false))
	manager:add_action (operators["search_corpse"], action)

	action = manager:action (xr_actions_id.alife)
	action:add_precondition		(world_property(properties["corpse_exist"],		false))

	action = manager:action (operators["state_mgr_to_idle_alife"])
	action:add_precondition		(world_property(properties["corpse_exist"],		false))
end

function set_corpse_detection(npc, ini, scheme, section)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
end


function reset_corpse_detection(npc, scheme, st, section)
	st.corpse_detection.corpse_detection_enabled = utils.cfg_get_bool(st.ini, section, "corpse_detection_enabled", npc, false, true)
end

function is_under_corpse_detection(npc)
	local mgr = npc:motivation_action_manager()

	if not mgr:initialized() then
		return false
	end

	local current_action_id = mgr:current_action_id() 
	return  current_action_id == xr_actions_id.corpse_exist
end